<a href="https://colab.research.google.com/github/BrentMRPalmer/PyTorchZTM/blob/main/S2Fundamentals/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10],
                       [111, 12]])
MATRIX

tensor([[  7,   8],
        [  9,  10],
        [111,  12]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]],
                       [[2, 6, 3],
                        [4, 5, 6],
                        [55, 2, 1]]])

TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  5,  4]],

        [[ 2,  6,  3],
         [ 4,  5,  6],
         [55,  2,  1]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([2, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [15]:
TENSOR[1][2][1]

tensor(2)

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers, and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5722, 0.3987, 0.1404, 0.6613],
        [0.2801, 0.0781, 0.1176, 0.9473],
        [0.6021, 0.0463, 0.4744, 0.2234]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [19]:
ran_tensor = torch.rand(2,3,4,5)
ran_tensor

tensor([[[[0.8154, 0.6836, 0.3560, 0.8604, 0.0775],
          [0.7665, 0.2781, 0.5008, 0.6947, 0.5726],
          [0.5183, 0.2896, 0.1236, 0.2214, 0.3470],
          [0.6992, 0.9296, 0.6129, 0.1034, 0.2186]],

         [[0.7567, 0.4923, 0.0024, 0.6777, 0.9444],
          [0.2999, 0.9021, 0.9566, 0.2393, 0.2245],
          [0.7452, 0.0754, 0.4607, 0.7947, 0.4812],
          [0.3330, 0.0744, 0.2813, 0.2925, 0.8696]],

         [[0.0905, 0.3931, 0.2122, 0.7939, 0.6725],
          [0.8143, 0.9408, 0.7267, 0.2353, 0.9878],
          [0.3767, 0.4234, 0.4125, 0.5672, 0.8497],
          [0.5294, 0.6338, 0.6662, 0.9623, 0.6248]]],


        [[[0.3326, 0.7135, 0.9461, 0.6339, 0.6528],
          [0.0321, 0.1303, 0.1935, 0.8796, 0.7526],
          [0.8099, 0.2455, 0.3898, 0.6314, 0.2730],
          [0.3311, 0.3744, 0.6766, 0.1831, 0.7544]],

         [[0.3263, 0.4571, 0.1874, 0.3697, 0.9296],
          [0.4084, 0.3210, 0.8623, 0.3544, 0.2940],
          [0.2777, 0.4589, 0.8847, 0.8434, 0.6737],
  

### Zeroes and ones

In [20]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range() and get deprecated message, use torch.arange() instead
one_to_ten = torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big errors you will run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (), default is float32
                               device=None, # what device is your tensor on (cpu, gpu)
                               requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
mult = float_16_tensor * float_32_tensor
mult.dtype

torch.float32

In [31]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [34]:
# Create a tensor
some_tensor = torch.rand(size=(3, 4), device="cpu")
some_tensor

tensor([[0.1561, 0.8689, 0.6578, 0.7451],
        [0.2668, 0.8450, 0.7666, 0.2634],
        [0.9870, 0.0930, 0.3515, 0.1215]])

In [35]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1561, 0.8689, 0.6578, 0.7451],
        [0.2668, 0.8450, 0.7666, 0.2634],
        [0.9870, 0.0930, 0.3515, 0.1215]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplcation (element-wise)
* Division
* Matrix multiplication

In [38]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [41]:
# Try out PyTorch built-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [43]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])